{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "3d364032-955a-4db7-a958-83997eac96e9",
   "metadata": {},
   "source": [
    "# Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "\n",
    "We use the Exception class as the base class when creating custom exceptions in Python for several reasons:\n",
    "\n",
    "- The Exception class is the parent class for all built-in exceptions in Python. By inheriting from the Exception class, our custom exception inherits all the behaviors and properties defined by the Exception class and its superclasses. This includes attributes like the error message, stack trace, and methods like __str__() for string representation and __repr__() for debugging purposes.\n",
    "\n",
    "- By using the Exception class as the base class, we ensure that our custom exceptions adhere to the established exception hierarchy in Python. This consistency allows for standardized exception handling and promotes code readability and maintainability. It also allows our custom exceptions to be caught by generic exception handlers that handle exceptions of the Exception type.\n",
    "\n",
    "- By inheriting from the Exception class, our custom exceptions can be used interchangeably with other built-in exceptions and integrated seamlessly into existing exception handling mechanisms. This compatibility ensures that our custom exceptions can be handled and processed using the same techniques and patterns used for handling other exceptions.\n",
    "\n",
    "-  Using the Exception class as the base class for custom exceptions is considered a best practice in Python. It follows the principle of code reuse and adheres to the conventions established by the Python language. It also allows for easier comprehension by other developers who are familiar with the standard exception hierarchy.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6dad6403-0a09-4602-b81d-83cdba56ab02",
   "metadata": {},
   "source": [
    "# Q2.Write a python program to print Python Exception Hierarchy."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "c5678ae6-85bb-481d-a65b-7942f9d2954f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " 'BaseException'\n",
      "   'Exception'\n",
      "     'TypeError'\n",
      "       'decimal.FloatOperation'\n",
      "       'email.errors.MultipartConversionError'\n",
      "     'StopAsyncIteration'\n",
      "     'StopIteration'\n",
      "     'ImportError'\n",
      "       'ModuleNotFoundError'\n",
      "       'zipimport.ZipImportError'\n",
      "     'OSError'\n",
      "       'ConnectionError'\n",
      "         'BrokenPipeError'\n",
      "         'ConnectionAbortedError'\n",
      "         'ConnectionRefusedError'\n",
      "         'ConnectionResetError'\n",
      "           'http.client.RemoteDisconnected'\n",
      "       'BlockingIOError'\n",
      "       'ChildProcessError'\n",
      "       'FileExistsError'\n",
      "       'FileNotFoundError'\n",
      "       'IsADirectoryError'\n",
      "       'NotADirectoryError'\n",
      "       'InterruptedError'\n",
      "         'zmq.error.InterruptedSystemCall'\n",
      "       'PermissionError'\n",
      "       'ProcessLookupError'\n",
      "       'TimeoutError'\n",
      "       'io.UnsupportedOperation'\n",
      "       'signal.itimer_error'\n",
      "       'socket.herror'\n",
      "       'socket.gaierror'\n",
      "       'ssl.SSLError'\n",
      "         'ssl.SSLCertVerificationError'\n",
      "         'ssl.SSLZeroReturnError'\n",
      "         'ssl.SSLWantWriteError'\n",
      "         'ssl.SSLWantReadError'\n",
      "         'ssl.SSLSyscallError'\n",
      "         'ssl.SSLEOFError'\n",
      "       'shutil.Error'\n",
      "         'shutil.SameFileError'\n",
      "       'shutil.SpecialFileError'\n",
      "       'shutil.ExecError'\n",
      "       'shutil.ReadError'\n",
      "       'urllib.error.URLError'\n",
      "         'urllib.error.HTTPError'\n",
      "         'urllib.error.ContentTooShortError'\n",
      "       'gzip.BadGzipFile'\n",
      "     'EOFError'\n",
      "       'asyncio.exceptions.IncompleteReadError'\n",
      "     'RuntimeError'\n",
      "       'RecursionError'\n",
      "       'NotImplementedError'\n",
      "         'zmq.error.ZMQVersionError'\n",
      "         'IPython.core.error.StdinNotImplementedError'\n",
      "       '_frozen_importlib._DeadlockError'\n",
      "       'threading.BrokenBarrierError'\n",
      "       'concurrent.futures._base.BrokenExecutor'\n",
      "         'concurrent.futures.thread.BrokenThreadPool'\n",
      "       'asyncio.exceptions.SendfileNotAvailableError'\n",
      "       'pkg_resources.ExtractionError'\n",
      "       '_pydevd_bundle.pydevd_vars.VariableError'\n",
      "     'NameError'\n",
      "       'UnboundLocalError'\n",
      "     'AttributeError'\n",
      "       'dataclasses.FrozenInstanceError'\n",
      "     'SyntaxError'\n",
      "       'IndentationError'\n",
      "         'TabError'\n",
      "     'LookupError'\n",
      "       'IndexError'\n",
      "       'KeyError'\n",
      "         'jupyter_client.kernelspec.NoSuchKernel'\n",
      "         'IPython.terminal.pt_inputhooks.UnknownBackend'\n",
      "       'encodings.CodecRegistryError'\n",
      "     'ValueError'\n",
      "       'UnicodeError'\n",
      "         'UnicodeEncodeError'\n",
      "         'UnicodeDecodeError'\n",
      "         'UnicodeTranslateError'\n",
      "       'io.UnsupportedOperation'\n",
      "       'json.decoder.JSONDecodeError'\n",
      "       'ssl.SSLCertVerificationError'\n",
      "       'binascii.Error'\n",
      "       '_hashlib.UnsupportedDigestmodError'\n",
      "       'calendar.IllegalMonthError'\n",
      "       'calendar.IllegalWeekdayError'\n",
      "       'dateutil.parser._parser.ParserError'\n",
      "       'pygments.util.ClassNotFound'\n",
      "       'IPython.lib.clipboard.ClipboardEmpty'\n",
      "       'email.errors.MessageDefect'\n",
      "         'email.errors.NoBoundaryInMultipartDefect'\n",
      "         'email.errors.StartBoundaryNotFoundDefect'\n",
      "         'email.errors.CloseBoundaryNotFoundDefect'\n",
      "         'email.errors.FirstHeaderLineIsContinuationDefect'\n",
      "         'email.errors.MisplacedEnvelopeHeaderDefect'\n",
      "         'email.errors.MissingHeaderBodySeparatorDefect'\n",
      "         'email.errors.MultipartInvariantViolationDefect'\n",
      "         'email.errors.InvalidMultipartContentTransferEncodingDefect'\n",
      "         'email.errors.UndecodableBytesDefect'\n",
      "         'email.errors.InvalidBase64PaddingDefect'\n",
      "         'email.errors.InvalidBase64CharactersDefect'\n",
      "         'email.errors.InvalidBase64LengthDefect'\n",
      "         'email.errors.HeaderDefect'\n",
      "           'email.errors.InvalidHeaderDefect'\n",
      "           'email.errors.HeaderMissingRequiredValue'\n",
      "           'email.errors.NonPrintableDefect'\n",
      "           'email.errors.ObsoleteHeaderDefect'\n",
      "           'email.errors.NonASCIILocalPartDefect'\n",
      "           'email.errors.InvalidDateDefect'\n",
      "       'IPython.core.magics.code.MacroToEdit'\n",
      "       'plistlib.InvalidFileException'\n",
      "       'pkg_resources._vendor.more_itertools.more.UnequalIterablesError'\n",
      "       'pkg_resources.extern.packaging.version.InvalidVersion'\n",
      "       'pkg_resources._vendor.packaging._manylinux._ELFFileHeader._InvalidELFFileHeader'\n",
      "       'pkg_resources.extern.packaging.utils.InvalidWheelFilename'\n",
      "       'pkg_resources.extern.packaging.utils.InvalidSdistFilename'\n",
      "       'pkg_resources.extern.packaging.specifiers.InvalidSpecifier'\n",
      "       'pkg_resources.extern.packaging.markers.InvalidMarker'\n",
      "       'pkg_resources.extern.packaging.markers.UndefinedComparison'\n",
      "       'pkg_resources.extern.packaging.markers.UndefinedEnvironmentName'\n",
      "       'pkg_resources.extern.packaging.requirements.InvalidRequirement'\n",
      "         'pkg_resources.RequirementParseError'\n",
      "       'packaging.version.InvalidVersion'\n",
      "     'AssertionError'\n",
      "     'ArithmeticError'\n",
      "       'FloatingPointError'\n",
      "       'OverflowError'\n",
      "       'ZeroDivisionError'\n",
      "         'decimal.DivisionByZero'\n",
      "         'decimal.DivisionUndefined'\n",
      "       'decimal.DecimalException'\n",
      "         'decimal.Clamped'\n",
      "         'decimal.Rounded'\n",
      "           'decimal.Underflow'\n",
      "           'decimal.Overflow'\n",
      "         'decimal.Inexact'\n",
      "           'decimal.Underflow'\n",
      "           'decimal.Overflow'\n",
      "         'decimal.Subnormal'\n",
      "           'decimal.Underflow'\n",
      "         'decimal.DivisionByZero'\n",
      "         'decimal.FloatOperation'\n",
      "         'decimal.InvalidOperation'\n",
      "           'decimal.ConversionSyntax'\n",
      "           'decimal.DivisionImpossible'\n",
      "           'decimal.DivisionUndefined'\n",
      "           'decimal.InvalidContext'\n",
      "     'SystemError'\n",
      "       'encodings.CodecRegistryError'\n",
      "     'ReferenceError'\n",
      "     'MemoryError'\n",
      "     'BufferError'\n",
      "     'Warning'\n",
      "       'UserWarning'\n",
      "         'getpass.GetPassWarning'\n",
      "         'IPython.core.formatters.FormatterWarning'\n",
      "       'EncodingWarning'\n",
      "       'DeprecationWarning'\n",
      "         'IPython.core.interactiveshell.ProvisionalWarning'\n",
      "       'PendingDeprecationWarning'\n",
      "       'SyntaxWarning'\n",
      "       'RuntimeWarning'\n",
      "         'zmq.asyncio.ProactorSelectorThreadWarning'\n",
      "         'dateutil.parser._parser.UnknownTimezoneWarning'\n",
      "         'pkg_resources.PEP440Warning'\n",
      "       'FutureWarning'\n",
      "         'IPython.core.completer.ProvisionalCompleterWarning'\n",
      "       'ImportWarning'\n",
      "       'UnicodeWarning'\n",
      "       'BytesWarning'\n",
      "       'ResourceWarning'\n",
      "       'dateutil.tz.DeprecatedTzFormatWarning'\n",
      "       'pkg_resources.PkgResourcesDeprecationWarning'\n",
      "     'warnings._OptionError'\n",
      "     'runpy._Error'\n",
      "     're.error'\n",
      "     'sre_parse.Verbose'\n",
      "     'locale.Error'\n",
      "     'subprocess.SubprocessError'\n",
      "       'subprocess.CalledProcessError'\n",
      "       'subprocess.TimeoutExpired'\n",
      "     'tokenize.TokenError'\n",
      "     'tokenize.StopTokenizing'\n",
      "     'inspect.ClassFoundException'\n",
      "     'inspect.EndOfBlock'\n",
      "     'traitlets.traitlets.TraitError'\n",
      "     'copy.Error'\n",
      "     'concurrent.futures._base.Error'\n",
      "       'concurrent.futures._base.CancelledError'\n",
      "       'concurrent.futures._base.TimeoutError'\n",
      "       'concurrent.futures._base.InvalidStateError'\n",
      "     'socket._GiveupOnSendfile'\n",
      "     'struct.error'\n",
      "     'binascii.Incomplete'\n",
      "     'asyncio.exceptions.TimeoutError'\n",
      "     'asyncio.exceptions.InvalidStateError'\n",
      "     'asyncio.exceptions.LimitOverrunError'\n",
      "     'asyncio.queues.QueueEmpty'\n",
      "     'asyncio.queues.QueueFull'\n",
      "     '_queue.Empty'\n",
      "     'queue.Full'\n",
      "     'ctypes.ArgumentError'\n",
      "     'zmq.error.ZMQBaseError'\n",
      "       'zmq.error.ZMQError'\n",
      "         'zmq.error.ContextTerminated'\n",
      "         'zmq.error.Again'\n",
      "         'zmq.error.InterruptedSystemCall'\n",
      "       'zmq.error.ZMQBindError'\n",
      "       'zmq.error.NotDone'\n",
      "     '_pickle.PickleError'\n",
      "       '_pickle.PicklingError'\n",
      "       '_pickle.UnpicklingError'\n",
      "     'pickle._Stop'\n",
      "     'argparse.ArgumentError'\n",
      "     'argparse.ArgumentTypeError'\n",
      "     'traitlets.config.loader.ConfigError'\n",
      "       'traitlets.config.loader.ConfigLoaderError'\n",
      "         'traitlets.config.loader.ArgumentError'\n",
      "       'traitlets.config.loader.ConfigFileNotFound'\n",
      "     'traitlets.config.configurable.ConfigurableError'\n",
      "       'traitlets.config.configurable.MultipleInstanceError'\n",
      "     'traitlets.config.application.ApplicationError'\n",
      "     'zlib.error'\n",
      "     'tornado.util.TimeoutError'\n",
      "     '_curses.error'\n",
      "     'tornado.concurrent.ReturnValueIgnoredError'\n",
      "     'tornado.gen.KeyReuseError'\n",
      "     'tornado.gen.UnknownKeyError'\n",
      "     'tornado.gen.LeakedCallbackError'\n",
      "     'tornado.gen.BadYieldError'\n",
      "     'tornado.gen.ReturnValueIgnoredError'\n",
      "     'tornado.gen.Return'\n",
      "     'jupyter_client.channels.InvalidPortNumber'\n",
      "     'termios.error'\n",
      "     '_lzma.LZMAError'\n",
      "     'shutil.RegistryError'\n",
      "     'shutil._GiveupOnFastCopy'\n",
      "     'configparser.Error'\n",
      "       'configparser.NoSectionError'\n",
      "       'configparser.DuplicateSectionError'\n",
      "       'configparser.DuplicateOptionError'\n",
      "       'configparser.NoOptionError'\n",
      "       'configparser.InterpolationError'\n",
      "         'configparser.InterpolationMissingOptionError'\n",
      "         'configparser.InterpolationSyntaxError'\n",
      "         'configparser.InterpolationDepthError'\n",
      "       'configparser.ParsingError'\n",
      "         'configparser.MissingSectionHeaderError'\n",
      "     'jupyter_client.localinterfaces.NoIPAddresses'\n",
      "     'zipfile.BadZipFile'\n",
      "     'zipfile.LargeZipFile'\n",
      "     'entrypoints.BadEntryPoint'\n",
      "     'entrypoints.NoSuchEntryPoint'\n",
      "     'jupyter_client.multikernelmanager.DuplicateKernelError'\n",
      "     'pydoc.ErrorDuringImport'\n",
      "     'executing.executing.NotOneValueFound'\n",
      "     'pure_eval.utils.CannotEval'\n",
      "     'pygments.util.OptionError'\n",
      "     'bdb.BdbQuit'\n",
      "     'pdb.Restart'\n",
      "     'pexpect.exceptions.ExceptionPexpect'\n",
      "       'pexpect.exceptions.EOF'\n",
      "       'pexpect.exceptions.TIMEOUT'\n",
      "     'ptyprocess.util.PtyProcessError'\n",
      "     'IPython.utils.process.FindCmdError'\n",
      "     'IPython.utils.path.HomeDirError'\n",
      "     'IPython.core.profiledir.ProfileDirError'\n",
      "     'IPython.core.error.IPythonCoreError'\n",
      "       'IPython.core.error.TryNext'\n",
      "       'IPython.core.error.UsageError'\n",
      "       'IPython.core.error.StdinNotImplementedError'\n",
      "     'IPython.core.error.InputRejected'\n",
      "     'getopt.GetoptError'\n",
      "     'pygments.filters.ErrorToken'\n",
      "     'IPython.core.prefilter.PrefilterError'\n",
      "     'IPython.core.alias.AliasError'\n",
      "       'IPython.core.alias.InvalidAliasError'\n",
      "     'sqlite3.Error'\n",
      "       'sqlite3.InterfaceError'\n",
      "       'sqlite3.DatabaseError'\n",
      "         'sqlite3.InternalError'\n",
      "         'sqlite3.OperationalError'\n",
      "         'sqlite3.ProgrammingError'\n",
      "         'sqlite3.IntegrityError'\n",
      "         'sqlite3.DataError'\n",
      "         'sqlite3.NotSupportedError'\n",
      "     'sqlite3.Warning'\n",
      "     'IPython.core.interactiveshell.SpaceInInput'\n",
      "     'xml.dom.DOMException'\n",
      "       'xml.dom.IndexSizeErr'\n",
      "       'xml.dom.DomstringSizeErr'\n",
      "       'xml.dom.HierarchyRequestErr'\n",
      "       'xml.dom.WrongDocumentErr'\n",
      "       'xml.dom.InvalidCharacterErr'\n",
      "       'xml.dom.NoDataAllowedErr'\n",
      "       'xml.dom.NoModificationAllowedErr'\n",
      "       'xml.dom.NotFoundErr'\n",
      "       'xml.dom.NotSupportedErr'\n",
      "       'xml.dom.InuseAttributeErr'\n",
      "       'xml.dom.InvalidStateErr'\n",
      "       'xml.dom.SyntaxErr'\n",
      "       'xml.dom.InvalidModificationErr'\n",
      "       'xml.dom.NamespaceErr'\n",
      "       'xml.dom.InvalidAccessErr'\n",
      "       'xml.dom.ValidationErr'\n",
      "     'prompt_toolkit.validation.ValidationError'\n",
      "     'prompt_toolkit.buffer.EditReadOnlyBuffer'\n",
      "     'prompt_toolkit.buffer._Retry'\n",
      "     'prompt_toolkit.layout.layout.InvalidLayoutError'\n",
      "     'prompt_toolkit.renderer.HeightIsUnknownError'\n",
      "     'parso.parser.ParserSyntaxError'\n",
      "     'parso.parser.InternalParseError'\n",
      "     'parso.python.diff._PositionUpdatingFinished'\n",
      "     'jedi.inference.helpers.SimpleGetItemNotFound'\n",
      "     'jedi.inference.utils.UncaughtAttributeError'\n",
      "     'jedi.inference.base_value.HasNoContext'\n",
      "     'jedi.inference.arguments.ParamIssue'\n",
      "     'jedi.api.exceptions._JediError'\n",
      "       'jedi.api.exceptions.InternalError'\n",
      "       'jedi.api.exceptions.WrongVersion'\n",
      "       'jedi.api.exceptions.RefactoringError'\n",
      "     'jedi.api.helpers.OnErrorLeaf'\n",
      "     'jedi.api.environment.InvalidPythonEnvironment'\n",
      "     'email.errors.MessageError'\n",
      "       'email.errors.MessageParseError'\n",
      "         'email.errors.HeaderParseError'\n",
      "         'email.errors.BoundaryError'\n",
      "       'email.errors.MultipartConversionError'\n",
      "       'email.errors.CharsetError'\n",
      "     'uu.Error'\n",
      "     'http.client.HTTPException'\n",
      "       'http.client.NotConnected'\n",
      "       'http.client.InvalidURL'\n",
      "       'http.client.UnknownProtocol'\n",
      "       'http.client.UnknownTransferEncoding'\n",
      "       'http.client.UnimplementedFileMode'\n",
      "       'http.client.IncompleteRead'\n",
      "       'http.client.ImproperConnectionState'\n",
      "         'http.client.CannotSendRequest'\n",
      "         'http.client.CannotSendHeader'\n",
      "         'http.client.ResponseNotReady'\n",
      "       'http.client.BadStatusLine'\n",
      "         'http.client.RemoteDisconnected'\n",
      "       'http.client.LineTooLong'\n",
      "     'IPython.core.magics.code.InteractivelyDefined'\n",
      "     'IPython.terminal.embed.KillEmbedded'\n",
      "     'psutil.Error'\n",
      "       'psutil.NoSuchProcess'\n",
      "         'psutil.ZombieProcess'\n",
      "       'psutil.AccessDenied'\n",
      "       'psutil.TimeoutExpired'\n",
      "     'psutil._pslinux._Ipv6UnsupportedError'\n",
      "     'tornado.queues.QueueEmpty'\n",
      "     'tornado.queues.QueueFull'\n",
      "     '_pydev_bundle._pydev_saved_modules.DebuggerInitializationError'\n",
      "     'xml.parsers.expat.ExpatError'\n",
      "     'xmlrpc.client.Error'\n",
      "       'xmlrpc.client.ProtocolError'\n",
      "       'xmlrpc.client.ResponseError'\n",
      "       'xmlrpc.client.Fault'\n",
      "     'pkg_resources._vendor.pyparsing.exceptions.ParseBaseException'\n",
      "       'pkg_resources._vendor.pyparsing.exceptions.ParseException'\n",
      "       'pkg_resources._vendor.pyparsing.exceptions.ParseFatalException'\n",
      "         'pkg_resources._vendor.pyparsing.exceptions.ParseSyntaxException'\n",
      "     'pkg_resources._vendor.pyparsing.exceptions.RecursiveGrammarException'\n",
      "     'pkg_resources.ResolutionError'\n",
      "       'pkg_resources.VersionConflict'\n",
      "         'pkg_resources.ContextualVersionConflict'\n",
      "       'pkg_resources.DistributionNotFound'\n",
      "       'pkg_resources.UnknownExtra'\n",
      "     '_pydevd_bundle.pydevd_runpy._Error'\n",
      "     '_pydevd_bundle.pydevd_resolver.UnableToResolveVariableException'\n",
      "     '_pydev_bundle.pydev_monkey.InvalidTypeInArgsException'\n",
      "   'GeneratorExit'\n",
      "   'SystemExit'\n",
      "   'KeyboardInterrupt'\n",
      "   'asyncio.exceptions.CancelledError'\n",
      "   'pkg_resources._vendor.more_itertools.more.AbortThread'\n"
     ]
    }
   ],
   "source": [
    "def hierarchy(exception_class,indent=0):\n",
    "    print(' '*indent + str(exception_class)[6:-1])\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        hierarchy(subclass,indent+2)\n",
    "\n",
    "hierarchy(BaseException)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2547baf8-929e-4a1b-91e5-a30dacd2a1e4",
   "metadata": {},
   "source": [
    "# Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.\n",
    "\n",
    "The ArithmeticError class in Python is a base class for errors that occur during arithmetic calculations. It defines several specific errors that can be encountered during arithmetic operations.\n",
    "\n",
    "The errors defined in the ArithmeticError class are:\n",
    "\n",
    "- OverflowError\n",
    "- FloatingPointError\n",
    "- ZeroDivisionError"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "24bbcdfc-432d-47e2-84a0-7bf2c3c05eec",
   "metadata": {},
   "source": [
    "- <b><u>ZeroDivisionError:</u></b> This error is raised when there is an attempt to divide a number by zero."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "418f307a-af90-404a-9e76-8ffc71dc7c71",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "division by zero <class 'ZeroDivisionError'>\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    10/0\n",
    "except ArithmeticError as e:\n",
    "    print(e,type(e))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d1a123cf-977a-4527-9434-f6365fdbaa98",
   "metadata": {},
   "source": [
    "- <b><u>OverflowError:</u></b> This error is raised when the result of an arithmetic operation exceeds the maximum representable value for a numeric type."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "2abdb661-fa03-4973-aa01-fae6716265ae",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "math range error <class 'OverflowError'>\n"
     ]
    }
   ],
   "source": [
    "import math\n",
    "try:\n",
    "    math.exp(1000)\n",
    "except ArithmeticError as e:\n",
    "    print(e,type(e))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "945ad745-00be-497d-99d0-6dc3df9ecd45",
   "metadata": {},
   "source": [
    "# Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\n",
    "The LookupError class in Python is a base class for errors that occur when a lookup or indexing operation fails. It serves as a parent class for specific lookup-related errors.\n",
    "\n",
    "- <b><u>KeyError:</u></b> This error is raised when a dictionary key or set element is not found.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "536c1de5-81b0-4c15-ac68-759df4323b5c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1 <class 'KeyError'>\n"
     ]
    }
   ],
   "source": [
    "d={\"a\":\"b\"}\n",
    "try:\n",
    "    d[1]\n",
    "except LookupError as e:\n",
    "    print(e,type(e))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0674811b-9dd4-4193-bc9c-43b22ce667cf",
   "metadata": {},
   "source": [
    "- <b><u>IndexError:</u></b> This error is raised when a dictionary key or set element is not found."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "ccc34bc3-9e16-4ed5-9f03-016d5a63a11d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "list assignment index out of range <class 'IndexError'>\n"
     ]
    }
   ],
   "source": [
    "a=[1,2,3,4]\n",
    "try:\n",
    "    a[4]=3\n",
    "except LookupError as e:\n",
    "    print(e,type(e))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a13cd58b-35c8-406c-ab94-b35508215575",
   "metadata": {},
   "source": [
    "# Q5.Explain ImportError. What is ModuleNotFoundError?\n",
    "\n",
    "ImportError and ModuleNotFoundError are both exceptions that occur when there are issues with importing and locating modules in Python.\n",
    "\n",
    "- <b><u>ImportError:</u></b> This exception is raised when an imported module or a component of a module cannot be found or loaded. i.e., this error is raised even when a module is found but could not be loaded."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "d8a3cfbe-6d8e-4ec9-8fce-f42a0e698372",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "cannot import name 'A' from 'a1' (/home/jovyan/work/a1.py) <class 'ImportError'>\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    from a1 import A\n",
    "except ImportError as e:\n",
    "    print(e,type(e))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0e413bdf-2575-4f26-b7fb-c922c148c087",
   "metadata": {},
   "source": [
    "- <b><u>ModuleNotFoundError:</u></b> This exception is a subclass of ImportError and was introduced in Python 3.6. It is specifically raised when a module is not found during import.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "cee1a02a-3b71-4375-9060-b2564c0e5ecb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "No module named 'module' <class 'ModuleNotFoundError'>\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    import module\n",
    "except ImportError as e:\n",
    "    print(e,type(e))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a4211fb6-a3bc-44b3-af24-037ce6d46029",
   "metadata": {},
   "source": [
    "# Q6. List down some best practices for exception handling in python.\n",
    "\n",
    "- Be specific in exception handling: Catch specific exceptions rather than using a generic except block. This allows for targeted handling of specific exceptions and avoids unintentionally catching and hiding unrelated exceptions.\n",
    "\n",
    "- Use multiple except blocks: If you anticipate different types of exceptions, use multiple except blocks to handle them separately. This improves code readability and maintainability.\n",
    "\n",
    "- "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
